### PR TITLE
Restructured the project, added a React project, and added CORS.

### LINKED ISSUE #3: Initialize Front End Structure
Setup the front end portion of the project. All front end files should be stored in a sub-directory relative to the root. 

The directory should be initialized for a multi-page React app. The setup should include the following:

+ Dependency management (npm standard)
+ Documentation, including:
    + Build (if applicable)
    + Run
    + Install dependencies
+ Runnable React app (just the basic "hello world" is fine)

Anyone with front end knowledge, please comment any more necessary setup requirements.

### PR DESCRIPTION
**Pull request by McMackety**
I went ahead and bootstrapped a react project, restructured the folders to accommodate such a project, added CORS, and added the react project to the docker-compose.yml.

Additionally, I added a small demo to the react project and an API endpoint at /test in Django to show frontend->backend communication.

Fixes #3 and half of #4

### CODE REVIEW

**Comment by awhigham9** [comment]
Do the docker-compose commands in the README still apply after the changes to the Docker setup?

It seems like it should, but I wanted to check.

**Comment by McMackety** [comment]
Yeah, docker-compose up will always work if the changes to docker-compose.yml are valid.

**Comment by awhigham9** [comment]
I'll test on my end then approve it.

**Comment by McMackety** [comment]
Also, quick note, currently the CORS is configured to allow any origins. This needs to be reconfigured for production deployments. (Though honestly CORS should be handled by a properly made proxy hosting the Python daemon: like Traefik, Envoy, or NGINX)

**Comment by awhigham9** [comment]
Small Change:

I believe line 13 in `docker-compose.yml` needs the following change:

```docker-compose
build: backend/.
```

My build was failing until I made this change. Also, what platform are you running on?

**Comment by McMackety** [comment]
MacOS, that's probably why, I wrote it in the unix style.

**Comment by McMackety** [comment]
Whoops, nevermind, the image was cached and I forgot to change that line lol.

**Comment by McMackety** [comment]
Just pushed a fix

**Comment by awhigham9** [comment]
That fix looks good, it builds and the backend runs now.

**Comment by awhigham9** [comment]
One other issue, and this might just be on my end.

When I run `docker-compose up`, I receive the following error:

```shell
frontend_1  | 
frontend_1  | > gatorwiki-frontend@0.1.0 start
frontend_1  | > react-scripts start
frontend_1  |
frontend_1  | sh: react-scripts: not found
```

followed by the frontend container exiting. Do you know why this is?

**Comment by McMackety** [comment]
Just figured out the issue, the npm packages were being installed in the /code directory, which then got overridden by the /code volume. Fixed it by making the npm install run as a part of the start command instead of during the build.

**Pull request merged**
