### PR TITLE
Add Django and Docker setup with docs.

### PR DESCRIPTION
**Pull request by awhigham9**
Add basic Django project and Docker/Docker-Compose setup. Django app can now be launched with instructions in README.

These additions were tested on Windows 10 and Ubuntu 18.04 within WSL 2.0. Further testing on MacOS and native Linux recommended, although it should be cross-platform.

### CODE REVIEW

**Comment by awhigham9** [comment]
The settings.py and other files will need changes before going into production for security, but I think they'll suffice for now? I'd appreciate some feedback on this.

**Comment by awhigham9** [comment]
I'm going to merge the PR so we can the basic structure setup. We can circle back on any issues and solve them in later work.

**Comment by McMackety** [comment]
This overall looks good to me, I'd recommend adding CORS to the Django API as it will be necessary when writing any front end code. (As the front end and backend are served from different ports.) In addition I don't know if you want to put the front end in a this repository or split the front end and backend into two separate repositories. Though you should at least bootstrap the create-react-app project.

**Comment by awhigham9** [comment]
@McMackety I think we are going to be putting the front end in the same repository for now, but deploying it as a separate instance. You're definitely right that we'll need CORS as you said, since we will be hosting on two domains. I will open issues for this and initializing the react app portion. Thanks!

**Pull request merged**
